### PR TITLE
Talos 3d

### PR DESCRIPTION
**Pull request by Tom-Ski**

### CODE REVIEW

**Comment by yuripourre** [comment]
Why!?!?!

**Comment by yuripourre** [comment]
@Tom-Ski hey, there are any plans to make Talos 3D? I am very interested on that.

**Comment by Tom-Ski** [comment]
Yeah. This is the future branch of the project being actively developed.  The PR was just for me to check a diff between main in a very lazy way.

**Comment by Tom-Ski** [comment]
You'll be able to play with this branch on the website in the browser very soon

**Comment by yuripourre** [comment]
@Tom-Ski 😍

**Pull request closed without merging**
